<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.1" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <None Include="runtimes/osx/native/libOpenCvSharpExtern.dylib">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>runtimes/osx/native/libOpenCvSharpExtern.dylib</TargetPath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bot.Core\Bot.Core.csproj" />
    <ProjectReference Include="..\Bot.Infrastructure\Bot.Infrastructure.csproj" />
    <ProjectReference Include="..\Bot.Tasks\Bot.Tasks.csproj" />
    <ProjectReference Include="..\Bot.Emulator\Bot.Emulator.csproj" />
    <ProjectReference Include="..\Bot.Vision\Bot.Vision.csproj" />
  </ItemGroup>
</Project>
